<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="119361" started-at="2020-02-27T12:58:14Z" finished-at="2020-02-27T13:00:14Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="119361" started-at="2020-02-27T12:58:14Z" finished-at="2020-02-27T13:00:14Z">
      <class name="com.training.retail.tests.TestCase5">
        <test-method status="PASS" signature="setUpBeforeClass()[pri:0, instance:com.training.retail.tests.TestCase5@482f8f11]" name="setUpBeforeClass" is-config="true" duration-ms="12" started-at="2020-02-27T18:28:14Z" finished-at="2020-02-27T18:28:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpBeforeClass -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.training.retail.tests.TestCase5@482f8f11]" name="setUp" is-config="true" duration-ms="63060" started-at="2020-02-27T18:28:14Z" finished-at="2020-02-27T18:29:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="validLoginTest()[pri:0, instance:com.training.retail.tests.TestCase5@482f8f11]" name="validLoginTest" duration-ms="54465" started-at="2020-02-27T18:29:17Z" finished-at="2020-02-27T18:30:12Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.training.retail.tests.TestCase5.validLoginTest(TestCase5.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validLoginTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.training.retail.tests.TestCase5@482f8f11]" name="tearDown" is-config="true" duration-ms="1799" started-at="2020-02-27T18:30:12Z" finished-at="2020-02-27T18:30:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.training.retail.tests.TestCase5 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
